# Generated by Django 4.2.11 on 2024-04-25 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirCraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_Number', models.CharField(max_length=32)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AirFare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('CNY', 'Chinese Yuan')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport', models.CharField(max_length=32)),
                ('destination', models.CharField(max_length=32)),
                ('rout_code', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statename', models.CharField(max_length=32, unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='booking.country')),
            ],
        ),
        migrations.CreateModel(
            name='FlightSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightDate', models.DateTimeField()),
                ('departure', models.DateTimeField()),
                ('arrival', models.DateTimeField()),
                ('airCraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircraft', to='booking.aircraft')),
                ('netFare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='netFare', to='booking.airfare')),
            ],
        ),
        migrations.AddField(
            model_name='airfare',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_of_airfare', to='booking.route'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='manufacture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mann', to='booking.manfact'),
        ),
    ]
