# Generated by Django 4.2.11 on 2024-04-26 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_airport_alter_route_airport_alter_route_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NEWAircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SeatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='capacity',
        ),
        migrations.AddField(
            model_name='aircraft',
            name='total_seats',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aircraft',
            name='seat_class',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.DO_NOTHING, related_name='seat_class', to='booking.seatcategory'),
            preserve_default=False,
        ),
    ]
