# Generated by Django 4.2.11 on 2024-04-26 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_class_newaircraft_seatcategory_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NEWAircraft',
        ),
    ]
