# Generated by Django 4.2.11 on 2024-04-26 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_manfact_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightschedule',
            old_name='arrival',
            new_name='arrival_time',
        ),
        migrations.RenameField(
            model_name='flightschedule',
            old_name='departure',
            new_name='departure_time',
        ),
        migrations.RemoveField(
            model_name='flightschedule',
            name='netFare',
        ),
        migrations.AddField(
            model_name='flightschedule',
            name='price_for_business',
            field=models.PositiveIntegerField(default=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flightschedule',
            name='price_for_econom',
            field=models.PositiveIntegerField(default=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flightschedule',
            name='price_for_premium',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flightschedule',
            name='route',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='route_of_flight', to='booking.route'),
            preserve_default=False,
        ),
    ]
