# Generated by Django 4.2.11 on 2024-04-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_rename_arrival_flightschedule_arrival_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightschedule',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('CNY', 'Chinese Yuan')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
