# Generated by Django 4.2.11 on 2024-04-27 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_rename_amount_of_columns_aircraft_amount_of_columns_business_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_class', models.CharField(choices=[('Econom', 'Economy Class'), ('Premium', 'Premium Class'), ('Business', 'Business Class')], max_length=10)),
                ('price', models.PositiveIntegerField()),
                ('seat_number', models.PositiveIntegerField()),
                ('window_seat', models.BooleanField(default=False)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='booking.flightschedule')),
            ],
        ),
        migrations.DeleteModel(
            name='AirFare',
        ),
    ]
