# Generated by Django 4.2.11 on 2024-04-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_ticket_delete_airfare'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightschedule',
            name='period',
            field=models.CharField(default='2h 30 m', max_length=100),
        ),
    ]
