# Generated by Django 4.2.11 on 2024-04-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_ticket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
